export const PRODUCT_CATEGORIES = [
  'Dairy, Bread & Eggs',
  'Rice, Flour & Pulses',
  'Cooking Oil & Ghee',
  'Spices, Masala & Salt',
  'Snacks & Namkeen',
  'Biscuits & Cookies',
  'Tea, Coffee & Beverages',
  'Breakfast & Instant Food',
  'Noodles, Pasta & Sauces',
  'Sweets & Chocolates',
  'Dry Fruits & Nuts',
  'Frozen Food',
  'Bakery Products',
  'Pickles, Chutneys & Papad',
  'Health & Nutrition',
  'Personal Care',
  'Household Cleaning',
  'Baby Care',
  'Pet Care',
  'Stationery & Daily Essentials',
  'Pooja Essentials',
];
